export const developerDocsCatalog = () => [
  {
    id: 'platform-integration-contracts',
    title: 'Platform Integration Contracts',
    category: 'contracts',
    path: '/docs/PLATFORM_INTEGRATION_CONTRACTS.md',
    description: 'Payment profiles, hosted challenge, payment intents, PaySafe lifecycle, webhooks, scopes.',
  },
  {
    id: 'developer-portal-contracts',
    title: 'Developer Portal Contracts',
    category: 'developer_portal',
    path: '/docs/DEVELOPER_PORTAL_CONTRACTS.md',
    description: 'Service onboarding, keys, secrets, scopes, consent receipts, allowlists, webhook delivery logs, health dashboard.',
  },
  {
    id: 'developer-portal-ui-blueprint',
    title: 'Developer Portal UI Blueprint',
    category: 'developer_portal',
    path: '/docs/DEVELOPER_PORTAL_UI_BLUEPRINT.md',
    description: 'Screen map, data sources, role access, and safety rules for the Developer Portal UI.',
  },
  {
    id: 'api-reference',
    title: 'API Reference',
    category: 'api',
    path: '/docs/API_REFERENCE.md',
    description: 'Gateway runtime and operator endpoint reference.',
  },
  {
    id: 'language-integration-configs',
    title: 'Language Integration Configs',
    category: 'sdk',
    path: '/docs/LANGUAGE_INTEGRATION_CONFIGS.md',
    description: 'Server-side configuration examples for Node.js, PHP, Laravel, Python, FastAPI, and cURL integrations.',
  },
  {
    id: 'developer-configuration-guide',
    title: 'Developer Configuration Guide',
    category: 'sdk',
    path: '/docs/DEVELOPER_CONFIGURATION_GUIDE.md',
    description: 'Practical environment variables, SDK setup, merchant readiness, sandbox simulation, webhooks, and go-live checklist.',
  },
  {
    id: 'openapi-spec',
    title: 'OpenAPI 3.1 Specification',
    category: 'api',
    path: '/docs/openapi/orbi-pay-gateway.openapi.json',
    description: 'Machine-readable API contract for developer portal browsing, generated SDKs, and API tools.',
  },
  {
    id: 'postman-collection',
    title: 'Postman And Insomnia Collection',
    category: 'api_tools',
    path: '/docs/postman/orbi-pay-gateway.postman_collection.json',
    description: 'Importable sandbox collection for checkout, hosted challenge, consent receipts, and webhook replay.',
  },
  {
    id: 'environment-separation',
    title: 'Sandbox And Live Separation',
    category: 'contracts',
    path: '/docs/SANDBOX_LIVE_SEPARATION.md',
    description: 'Trust-zone rules for sandbox vs live credentials, money movement, webhooks, and consent evidence.',
  },
  {
    id: 'graphql-migration-contract',
    title: 'GraphQL Migration Contract',
    category: 'contracts',
    path: '/docs/GRAPHQL_MIGRATION_CONTRACT.md',
    description: 'Contract-first path from REST to GraphQL without weakening auth, idempotency, consent, webhooks, or audit.',
  },
  {
    id: 'merchant-checkout-example',
    title: 'Merchant Checkout Example',
    category: 'examples',
    path: '/examples/merchant-checkout/README.md',
    description: 'Minimal Express example for checkout, hosted challenge redirect, signed webhooks, and order reconciliation.',
  },
  {
    id: 'seller-linking-example',
    title: 'Seller Linking Example',
    category: 'examples',
    path: '/examples/seller-linking/README.md',
    description: 'Minimal Express example for linking merchant-side sellers to ORBI payment profiles.',
  },
  {
    id: 'saccos-member-payments-example',
    title: 'SACCOS Member Payments Example',
    category: 'examples',
    path: '/examples/saccos-member-payments/README.md',
    description: 'Minimal Express example for member payment-profile linking, hosted payments, and signed webhook reconciliation.',
  },
  {
    id: 'contract-versioning-errors',
    title: 'Contract Versioning And Error Codes',
    category: 'contracts',
    path: '/docs/CONTRACT_VERSIONING_AND_ERROR_CODES.md',
    description: 'Stable response envelope, lifecycle states, and machine-readable errors.',
  },
  {
    id: 'security-model',
    title: 'Security Model',
    category: 'security',
    path: '/docs/SECURITY_MODEL.md',
    description: 'Secret handling, HMAC, worker trust, and provider credential boundaries.',
  },
  {
    id: 'deployment-runbook',
    title: 'Deployment Runbook',
    category: 'operations',
    path: '/docs/DEPLOYMENT_RUNBOOK.md',
    description: 'Self-hosted deployment and production operations guidance.',
  },
];

export const developerSandboxToolsCatalog = () => [
  {
    id: 'sandbox-service-application',
    title: 'Create Sandbox Service Application',
    status: 'available',
    endpoint: 'POST /v1/developer/service-applications',
    description: 'Submit a service/app application with sandbox environment.',
  },
  {
    id: 'sandbox-api-key',
    title: 'Issue Sandbox API Key',
    status: 'available',
    endpoint: 'POST /v1/developer/services/:serviceCode/api-keys/issue',
    description: 'Issue a one-time sandbox key after service approval.',
  },
  {
    id: 'sandbox-api-key-revoke',
    title: 'Revoke Sandbox API Key',
    status: 'available',
    endpoint: 'POST /v1/developer/services/:serviceCode/api-keys/:keyId/revoke',
    description: 'Emergency revoke an API key with operator reason and audit event.',
  },
  {
    id: 'sandbox-webhook-secret',
    title: 'Issue Sandbox Webhook Secret',
    status: 'available',
    endpoint: 'POST /v1/developer/services/:serviceCode/webhook-secrets/issue',
    description: 'Issue one-time sandbox webhook signing secret.',
  },
  {
    id: 'sandbox-webhook-secret-revoke',
    title: 'Revoke Sandbox Webhook Secret',
    status: 'available',
    endpoint: 'POST /v1/developer/services/:serviceCode/webhook-secrets/:secretId/revoke',
    description: 'Emergency revoke a webhook signing secret with operator reason and audit event.',
  },
  {
    id: 'sandbox-payment-intent',
    title: 'Test Payment Intent',
    status: 'contract_ready',
    endpoint: 'POST /v1/payment-intents',
    description: 'Create a test payment intent using sandbox service credentials.',
  },
  {
    id: 'environment-profiles',
    title: 'Sandbox/Live Environment Profiles',
    status: 'available',
    endpoint: '/v1/developer/environment-profiles',
    description: 'Read the explicit safety boundaries, key prefixes, money mode, provider mode, and webhook mode for sandbox and live.',
  },
  {
    id: 'sandbox-simulator-flow',
    title: 'Sandbox Simulator Flow',
    status: 'contract_ready',
    endpoint: '/v1/developer/sandbox-simulator',
    description: 'Developer-facing guide for simulating payment intents, hosted challenge approval/decline, signed webhooks, and replay.',
  },
  {
    id: 'graphql-schema-preview',
    title: 'GraphQL Schema Preview',
    status: 'contract_preview',
    endpoint: '/v1/developer/graphql/schema',
    description: 'Read the draft GraphQL schema. REST remains authoritative until GraphQL reaches parity gates.',
  },
  {
    id: 'postman-sandbox-collection',
    title: 'Postman Sandbox Collection',
    status: 'available',
    endpoint: '/docs/postman/orbi-pay-gateway.postman_collection.json',
    description: 'Import checkout, hosted challenge, consent, and webhook replay requests into Postman or Insomnia.',
  },
  {
    id: 'webhook-replay',
    title: 'Replay Failed Webhook',
    status: 'available',
    endpoint: 'POST /v1/developer/webhook-deliveries/:deliveryId/replay',
    description: 'Replay a signed webhook without changing ledger/payment state.',
  },
  {
    id: 'consent-receipts',
    title: 'Consent Receipt Evidence',
    status: 'available',
    endpoint: '/v1/developer/consent-receipts',
    description: 'Create, list, read, and revoke scoped consent evidence for sandbox or live services.',
  },
  {
    id: 'consent-scope-catalog',
    title: 'Consent Scope Catalog',
    status: 'available',
    endpoint: '/v1/developer/consent-scopes',
    description: 'Read localized scope labels, descriptions, risk levels, and hosted challenge requirements.',
  },
  {
    id: 'consent-status-check',
    title: 'Consent Status Check',
    status: 'available',
    endpoint: '/v1/developer/consent-status',
    description: 'Check whether consent is active, expiring soon, expired, revoked, or missing before prompting renewal.',
  },
  {
    id: 'obp-sandbox-tools',
    title: 'OBP Sandbox Discovery Tools',
    status: 'operator_toggle',
    endpoint: '/v1/discovery/obp/:providerCode/sandbox/*',
    description: 'Sandbox-only OBP banks, entitlements, and account tools guarded by PAYMENT_GATEWAY_OBP_SANDBOX_TOOLS_ENABLED.',
  },
];

export const developerSdkCatalog = () => [
  {
    id: 'node-sdk',
    language: 'TypeScript/Node.js',
    status: 'live_npm',
    packageName: '@orbifinancial/pay-gateway',
    docsPath: '/sdk/node/README.md',
    description: 'Live npm package with typed client and CLI for payment intents, PaySafe actions, webhook verification, and replay.',
  },
  {
    id: 'php-sdk',
    language: 'PHP',
    status: 'live_packagist',
    packageName: 'orbifinancial/pay-gateway',
    docsPath: '/sdk/php/README.md',
    description: 'Live Packagist package for PHP/Laravel commerce stacks.',
  },
  {
    id: 'python-sdk',
    language: 'Python',
    status: 'live_pypi',
    packageName: 'orbi-pay-gateway',
    docsPath: '/sdk/python/README.md',
    description: 'Live PyPI package for SACCOS, organizations, and custom back offices.',
  },
  {
    id: 'openapi-spec',
    language: 'OpenAPI',
    status: 'bootstrap_available',
    packageName: 'orbi-pay-gateway.openapi.json',
    docsPath: '/docs/openapi/orbi-pay-gateway.openapi.json',
    description: 'OpenAPI 3.1 contract for portal docs, SDK generation, and API tools.',
  },
];
